{% macro get_contact_history_columns() %}

{% set columns = [
    {"name": "_fivetran_deleted", "datatype": "boolean"},
    {"name": "_fivetran_synced", "datatype": dbt_utils.type_string()},
    {"name": "admin_id", "datatype": dbt_utils.type_int()},
    {"name": "android_app_name", "datatype": dbt_utils.type_int()},
    {"name": "android_app_version", "datatype": dbt_utils.type_int()},
    {"name": "android_device", "datatype": dbt_utils.type_int()},
    {"name": "android_last_seen_at", "datatype": dbt_utils.type_int()},
    {"name": "android_os_version", "datatype": dbt_utils.type_int()},
    {"name": "android_sdk_version", "datatype": dbt_utils.type_int()},
    {"name": "avatar", "datatype": dbt_utils.type_string()},
    {"name": "browser", "datatype": dbt_utils.type_string()},
    {"name": "browser_language", "datatype": dbt_utils.type_string()},
    {"name": "browser_version", "datatype": dbt_utils.type_string()},
    {"name": "created_at", "datatype": dbt_utils.type_string()},
    {"name": "custom_job_title", "datatype": dbt_utils.type_string()},
    {"name": "custom_onboarding_step", "datatype": dbt_utils.type_string()},
    {"name": "custom_organisation_id", "datatype": dbt_utils.type_string()},
    {"name": "custom_organisation_name", "datatype": dbt_utils.type_string()},
    {"name": "email", "datatype": dbt_utils.type_string()},
    {"name": "external_id", "datatype": dbt_utils.type_string()},
    {"name": "has_hard_bounced", "datatype": "boolean"},
    {"name": "id", "datatype": dbt_utils.type_string()},
    {"name": "ios_app_name", "datatype": dbt_utils.type_int()},
    {"name": "ios_app_version", "datatype": dbt_utils.type_int()},
    {"name": "ios_device", "datatype": dbt_utils.type_int()},
    {"name": "ios_last_seen_at", "datatype": dbt_utils.type_int()},
    {"name": "ios_os_version", "datatype": dbt_utils.type_int()},
    {"name": "ios_sdk_version", "datatype": dbt_utils.type_int()},
    {"name": "language_override", "datatype": dbt_utils.type_int()},
    {"name": "last_contacted_at", "datatype": dbt_utils.type_string()},
    {"name": "last_email_clicked_at", "datatype": dbt_utils.type_string()},
    {"name": "last_email_opened_at", "datatype": dbt_utils.type_string()},
    {"name": "last_replied_at", "datatype": dbt_utils.type_string()},
    {"name": "last_seen_at", "datatype": dbt_utils.type_string()},
    {"name": "location_city", "datatype": dbt_utils.type_string()},
    {"name": "location_country", "datatype": dbt_utils.type_string()},
    {"name": "location_region", "datatype": dbt_utils.type_string()},
    {"name": "marked_email_as_spam", "datatype": "boolean"},
    {"name": "name", "datatype": dbt_utils.type_string()},
    {"name": "os", "datatype": dbt_utils.type_string()},
    {"name": "phone", "datatype": dbt_utils.type_int()},
    {"name": "role", "datatype": dbt_utils.type_string()},
    {"name": "signed_up_at", "datatype": dbt_utils.type_string()},
    {"name": "unsubscribed_from_emails", "datatype": "boolean"},
    {"name": "updated_at", "datatype": dbt_utils.type_string()},
    {"name": "workspace_id", "datatype": dbt_utils.type_string()}
] %}

{{ return(columns) }}

{% endmacro %}
